// Shows how to best implement operator precedence in Lark

?start: sum
    | NAME "=" sum -> assign_var

?sum: product
    | sum "+" product -> add
    | sum "-" product -> sub

?product: atom
    | product "*" atom -> mul
    | product "/" atom -> div

?atom: NUMBER -> number
    | "-" atom -> neg
    | NAME -> var
    | "(" sum ")"

%import _common.CNAME -> NAME
%import _common.NUMBER
%import _common.WS_INLINE

%ignore WS_INLINE
